# Generated by Django 6.0.5 on 2026-05-19 16:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], db_index=True, default='UNPAID', max_length=10)),
                ('is_void', models.BooleanField(db_index=True, default=False)),
                ('cancel_reason', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='appointments.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
