# Generated by Django 6.0.5 on 2026-05-20 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must be 10–22 characters: digits, spaces, + or - only (e.g. 01711 123456).', regex='^[0-9+\\-\\s]{10,22}$')]),
        ),
    ]
